#426 Added pushing identifier changes to Openempi
Expose javascript methods for patient widget

ITNFA-30: Added possibility to change row selection handler in patientSearchWidget

ITNFA-30: Added 'Only in MPI' label

ITNFA-30: Changed label text to 'Not imported'

ITNFA-30: Added translations according to the Nathaelf's proposals

Adding support for coded obs and group obs in obsacrossencounters widget

RA-1001: Update all modules that use Transifex to support all languages we support (#130)

committing translations from transifex

Making conditionally loaded classes available for the entire platform
2.x

RA-1465: Move ConditionListUI to coreapps (#133)

* RA-1465: Move ConditionListUI to coreapps

fix includes on conditions widget

committing translations from transifex

RA-1465: Move ConditionListUI to coreapps (#135)

change AwaitingAdmissions report so that it formats all OpenMRS Objects within the report to avoid lazy loading exception at rendering time

Renaming some beans to avoid conflict with changes from TRUNK-5353

[maven-release-plugin] prepare release 1.19.0

[maven-release-plugin] prepare for next development iteration

TRUNK-5343: Create an api-2.2 sub module for the coreapps module. (#136)

patient search widget: don't clear results list until new search commences

TRUNK-5343: Create an api-pre2.2 sub module for the coreapps module. (#137)

TRUNK-5343: Create a new EncounterDiagnosesElement for the new api version 2.2 (#138)

Fixing failing tests for: TRUNK-5343: Create a new
EncounterDiagnosesElement for the new api-2.2

Deleting the shared EncounterDiagnosisElement such that it loads one
basing on the running platform: TRUNK-5343

Fixing NoClassDefFoundError for EncounterDiagnosesElement - TRUNK-5343

Fixing NPE when diagnosis existing obs is null - TRUNK-5343

TRUNK-5343: Update license header for EncounterDiagnosesElement.java in api-pre2.2 sub-module. (#139)

TRUNK-5343: Fix JSON parse error when existingObs is null. (#140)

obsacrossencounter: make getObservationsForConcept null-safe

updateSearchResults: make patient identifier null-safe

TRUNK-5343: Fix duplicating diagnoses when saving a visit note and implements deleting of diagnoses on a visit note (#141)

RA-1489: Formatted Obs Across Encounters for Concepts Dates and coded obs (#143)

TRUNK-5343: Fix the failure to delete an existing diagnosis when adding a new visit note (#144)

RA-1484 Changed the default value of the sticky notes GP to CIEL:165095

PROV-93, capture CHW birthdate (#145)

PROV-93, overwrite birthdate estimated field (#146)

* PROV-93, overwrite birthdate estimated field

* PROV-93, refactor with Boolean.TRUE

RA-1474: Coreapps: Patient Search Widget performed redundant search when running on OpenMRS 2.1.x (#142)

* RA-1474: Coreapps: Patient Search Widget performed redundant search when
running on OpenMRS 2.1.x

* Addressing changes proposed by Mr. Goodrich: changing code convention things that were missed, and added issue link in comments to added code.

* Removing unnecessary parameter

* gsp updates

Revert "RA-1474: Coreapps: Patient Search Widget performed redundant search when running on OpenMRS 2.1.x (#142)" (#148)

This reverts commit 2fcdc62026523154ab430d5a48179dc35b730f4c.

Enhancement to allow use of patient id or uuid when accessing mark patient dead page (#150)

Updated reference to SEDISH to MPI to make it more generic

[MPI-1] changed implementation of patientRegistrationEvents and Editted events to use OpenMRS Object CREATED and UPDATED subcribable events